FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY ./ ./
COPY Koggo.Client//appsettings.Development.json Koggo.Client/appsettings.json

RUN dotnet publish -c Release -o out  Koggo.Client/*.csproj
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "Koggo.Client.dll"]
